In [27]:
import numpy as np
import os, sys
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics

In [36]:
x_train = np.load(os.getcwd() + "/x_train.npy")
print(x_train)
y_train = np.load(os.getcwd() + "/y_train.npy")
print(y_train)

[[0.06741238 0.06666996 0.05018073 ... 0.00053681 0.00625812 0.00537487]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.06130948 0.01892311 0.05881432]
 ...
 [0.01512267 0.         0.         ... 0.         0.         0.00671988]
 [0.12196142 0.18785213 0.08513505 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]
[1 1 1 ... 0 0 0]


In [38]:
print("tamaño de las x de entrenamiento:")
print(x_train.shape)
print("tamaño de las y de entrenamiento:")
print(y_train.shape)

tamaño de las x de entrenamiento:
(3114, 8100)
tamaño de las y de entrenamiento:
(3114,)


In [40]:
clasifier = svm.SVC(kernel="linear") # kernel lineal

clasifier.fit(x_train, y_train) # entranamos el modelo

SVC(kernel='linear')

In [60]:
x_test = np.load(os.getcwd() + "/x_test.npy")
print(x_test)
y_test = np.load(os.getcwd() + "/y_test.npy")
print(y_test)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.04642025 0.00307377 0.         ... 0.         0.0072719  0.15840915]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]
[1 1 1 ... 0 0 0]


In [61]:
y_pred = clasifier.predict(x_test)

In [62]:
y_pred

array([1, 1, 1, ..., 0, 0, 0])

In [67]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:",metrics.precision_score(y_test, y_pred))

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:",metrics.recall_score(y_test, y_pred))

Accuracy: 0.971830985915493
Precision: 0.9687924016282226
Recall: 0.9794238683127572


In [79]:
# guardamos el modelo para usarlo
import joblib
from pathlib import Path

path_model = Path.cwd() # nos paramos en la direccion actual, ya que aqui deseo guardar el modelo

joblib.dump(clasifier, path_model / "svm_brain_model.joblib") # guardamos el modelo en la direccion indicada con el nombre
                                                              # "svm_brain_model.joblib"
print("El modelo se ha guardado en", path_model / "svm_brain_model.joblib")


El modelo se ha guardado en c:\Users\HP\Desktop\proc_dig_ima\Lab_02\Model\svm_brain_model.joblib
